Algoritmo "Area do triangulo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/03/2021
Var
// declaraçao de variaveis
base,altura,area:real


Inicio
// entrada
escreva("digite o tamanho da base")
leia(base)
escreva("Digite a altura do triangulo")
leia(altura)
//processo
area <- base*altura/2
//saida
escreva("A area do triangulo é ",area,"m2")



Fimalgoritmo