Algoritmo "trocarvariavel"
// 
//  
// Descrição   : ele troca valores
// Autor(a)    : Mateus Alves Moraes
// Data atual  : 22/03/2021
Var
   a,b,c: inteiro
Inicio
      a <- 88
      b <- 77
      escreval("O valor de A é: ", a)
      escreval("O valor de B é: ", b)

      c <- a
      a <- b
      b <- c

      escreval("O valor de A é: ", a)
      escreval("O valor de B é: ", b)

Fimalgoritmo