Algoritmo "15"
// Função :
// Autor :
// Data :
// Seção de Declarações
Var
escola:caracter
Inicio
escreval("Escreva o nome da MELHOR escola de Ribeirão Pires")
leia(escola)
enquanto escola <> "Etec MCM" faca
escreval
escreval("Resposta Errada. hmmm não é essa, tente de novo ;)")
leia(escola)
fimenquanto
se (escola = "Etec MCM")entao
escreval
escreval("Parabéns!!!!! Você acertou!")
fimse

Fimalgoritmo
