Algoritmo "7"
// Função :
// Autor :
// Data :
// Seção de Declarações
Var
contador, acumulador: inteiro
Inicio
escreval("Importante!")
escreval("")
escreval("O programa irá parar sua tarefa assim que o número digitado for")
escreval("ZXZXXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXZXXZXZXZXZXZXZXZXXZXZXZXZXZXZ")

repita
   escreval("Digite um número: ")

   acumulador <- ( acumulador + contador )
ate (contador <= 0)
escreval(acumulador)

Fimalgoritmo
