Algoritmo "areaquadrado"
// 
//  
// Descrição   : Calcular a area do quadrado
// Autor(a)    : Mateus Alves Moraes
// Data atual  : 02/03/2021
Var
//declaracao de variaveis
ladoquadrado,area: real

inicio
//Entrada
escreva("Digite o lado do quadrado")
leia(ladoquadrado)
//Processo
area <- ladoquadrado*ladoquadrado

//Saida
escreva("A area do quadrado é:",area," m2")


// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo